name: Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(date +%Y.%m.%d)
      - name: Build and push containers.monetr.dev
        uses: docker/build-push-action@v1
        with:
          registry: containers.monetr.dev
          username: ${{ secrets.containers_push_username }}
          password: ${{ secrets.containers_push_password }}
          tags: latest,${{ steps.tag.outputs.POST_TAG }}
          repository: deepsource
      - name: Build and push ghcr.io
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest,${{ steps.tag.outputs.POST_TAG }}
          repository: monetrapp/deepsource
